import { useEffect,useMemo,useRef,useState } from 'react'
import { Bold,Italic,List,ListOrdered,Image as ImageIcon,Plus,Save,Send,Table2,Trash2,Video,FileText,Users,X } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import MaterialViewer,{type MaterialRecord} from '../../components/MaterialViewer'
type Props={professorId:string}; type Student={id:string;nome_completo:string}
type EditorState={id:string|null;titulo:string;idioma:'ingles'|'alemao'|'';conteudo_html:string;imagens:string[];videos:string[];status:'rascunho'|'publicado'}
const empty:EditorState={id:null,titulo:'',idioma:'',conteudo_html:'<p><br /></p>',imagens:[],videos:[],status:'rascunho'}
export default function Materiais({professorId}:Props){
 const editorRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null)
 const [materials,setMaterials]=useState<MaterialRecord[]>([]),[students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState<string[]>([])
 const [editor,setEditor]=useState<EditorState>(empty),[open,setOpen]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[viewer,setViewer]=useState<MaterialRecord|null>(null),[imageUrls,setImageUrls]=useState<Record<string,string>>({}),[exitDialog,setExitDialog]=useState(false)
 const filtered=useMemo(()=>students.filter(s=>s.nome_completo.toLowerCase().includes(search.toLowerCase())),[students,search])
 async function load(){setLoading(true);try{const [m,a]=await Promise.all([supabase.from('materiais').select('id,titulo,idioma,conteudo_html,imagens,videos,status,created_at,updated_at,publicado_em').eq('professor_id',professorId).order('updated_at',{ascending:false}),supabase.from('alunos').select('id,nome_completo').eq('professor_id',professorId).order('nome_completo')]);if(m.error)throw m.error;if(a.error)throw a.error;setMaterials((m.data||[]) as MaterialRecord[]);setStudents(a.data||[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os materiais.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[professorId])
 useEffect(()=>{if(!open||!editor.id||!dirty)return;const t=window.setInterval(()=>{void save('rascunho',true)},30000);return()=>window.clearInterval(t)},[open,editor.id,dirty])
 function sync(){setEditor(v=>({...v,conteudo_html:editorRef.current?.innerHTML||v.conteudo_html}));setDirty(true)}
 function exec(command:string,value?:string){editorRef.current?.focus();document.execCommand(command,false,value);sync()}
 function table(){exec('insertHTML','<table><tbody><tr><th>Coluna 1</th><th>Coluna 2</th></tr><tr><td>Texto</td><td>Texto</td></tr></tbody></table><p><br/></p>')}
 async function upload(file:File){if(!editor.id){setError('Salve o material como rascunho antes de anexar uma imagem.');return}if(!file.type.startsWith('image/')){setError('Selecione uma imagem válida.');return}const name=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-'),path=professorId+'/'+editor.id+'/'+crypto.randomUUID()+'-'+name;const {error:e}=await supabase.storage.from('materiais').upload(path,file);if(e){setError(e.message);return}setEditor(v=>({...v,imagens:[...v.imagens,path]}));setDirty(true);setTimeout(()=>{editorRef.current?.focus();document.execCommand('insertHTML',false,'<p><img src="'+path+'" alt="'+file.name.replace(/"/g,'')+'"/></p>');sync()},0)}
 function video(){const url=window.prompt('Cole o link do vídeo (YouTube, Vimeo ou outro endereço HTTPS):');if(!url)return;if(!/^https:\/\//i.test(url)){setError('Informe um link HTTPS válido.');return}exec('insertHTML','<p><a href="'+url.replace(/"/g,'&quot;')+'" target="_blank" rel="noopener noreferrer">▶ Assistir vídeo</a></p>');setEditor(v=>({...v,videos:[...v.videos,url]}))}
 function newMaterial(){setEditor({...empty});setSelected([]);setDirty(false);setError('');setMessage('');setOpen(true);setTimeout(()=>{if(editorRef.current)editorRef.current.innerHTML=empty.conteudo_html},0)}
 async function edit(m:MaterialRecord){const {data}=await supabase.from('material_alunos').select('aluno_id').eq('material_id',m.id);setSelected((data||[]).map(r=>r.aluno_id));setEditor({id:m.id,titulo:m.titulo,idioma:m.idioma||'',conteudo_html:m.conteudo_html,imagens:m.imagens||[],videos:m.videos||[],status:m.status});setOpen(true);setDirty(false);setTimeout(()=>{if(editorRef.current)editorRef.current.innerHTML=m.conteudo_html},0)}
 async function save(status:'rascunho'|'publicado',silent=false){if(!editor.titulo.trim()){if(!silent)setError('Informe um título para o material.');return false}if(status==='publicado'&&!selected.length){setError('Selecione pelo menos um aluno para publicar.');return false}setSaving(true);setError('');try{const html=editorRef.current?.innerHTML||editor.conteudo_html;let id=editor.id;const payload={professor_id:professorId,titulo:editor.titulo.trim(),idioma:editor.idioma||null,conteudo_html:html,imagens:editor.imagens,videos:editor.videos,status,publicado_em:status==='publicado'?new Date().toISOString():null,updated_at:new Date().toISOString()};if(id){const {error:e}=await supabase.from('materiais').update(payload).eq('id',id);if(e)throw e}else{const {data,error:e}=await supabase.from('materiais').insert(payload).select('id').single();if(e)throw e;id=data.id;setEditor(v=>({...v,id}))}if(status==='publicado'){const {error:e}=await supabase.from('material_alunos').delete().eq('material_id',id);if(e)throw e;if(selected.length){const {error:e2}=await supabase.from('material_alunos').insert(selected.map(aluno_id=>({material_id:id!,aluno_id})));if(e2)throw e2}}setEditor(v=>({...v,id,status}));setDirty(false);await load();if(!silent)setMessage(status==='publicado'?'Material publicado para os alunos selecionados.':'Rascunho salvo com sucesso.');return true}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o material.');return false}finally{setSaving(false)}}
 function close(){if(dirty){setExitDialog(true);return}setOpen(false)}
 async function exit(saveDraft:boolean){if(saveDraft&&!await save('rascunho'))return;setExitDialog(false);setOpen(false);setDirty(false)}
 async function view(m:MaterialRecord){const entries=await Promise.all((m.imagens||[]).map(async p=>{const {data}=await supabase.storage.from('materiais').createSignedUrl(p,3600);return [p,data?.signedUrl||''] as const}));setImageUrls(Object.fromEntries(entries.filter(([,u])=>u)));setViewer(m)}
 async function remove(m:MaterialRecord){if(!window.confirm('Excluir "'+m.titulo+'"?'))return;const {error:e}=await supabase.from('materiais').delete().eq('id',m.id);if(e){setError(e.message);return}await load()}
 if(loading)return <div className="professor-materials-empty">Carregando materiais...</div>
 if(open)return <div className="professor-material-editor-page">
  <div className="professor-material-editor-header"><div><span className="professor-eyebrow">Material pedagógico</span><h1>{editor.id?'Editar material':'Novo material'}</h1><p>Texto, tabelas, formatação, imagens e vídeos para seus alunos.</p></div><button type="button" className="professor-secondary-button" onClick={close}><X size={17}/> Sair</button></div>
  <div className="professor-material-editor-grid"><main className="professor-material-editor-main">
   <div className="professor-material-editor-meta"><input className="professor-material-title-input" value={editor.titulo} onChange={e=>{setEditor(v=>({...v,titulo:e.target.value}));setDirty(true)}} placeholder="Título do material"/><select value={editor.idioma} onChange={e=>{setEditor(v=>({...v,idioma:e.target.value as EditorState['idioma']}));setDirty(true)}}><option value="">Idioma do material</option><option value="ingles">Inglês</option><option value="alemao">Alemão</option></select></div>
   <div className="professor-material-toolbar"><button type="button" onClick={()=>exec('bold')} title="Negrito"><Bold size={17}/></button><button type="button" onClick={()=>exec('italic')} title="Itálico"><Italic size={17}/></button><button type="button" onClick={()=>exec('insertUnorderedList')} title="Lista"><List size={17}/></button><button type="button" onClick={()=>exec('insertOrderedList')} title="Lista numerada"><ListOrdered size={17}/></button><button type="button" onClick={table} title="Tabela"><Table2 size={17}/></button><button type="button" onClick={()=>fileRef.current?.click()} title="Imagem"><ImageIcon size={17}/></button><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='' }}/><button type="button" onClick={video} title="Vídeo"><Video size={17}/></button></div>
   <div ref={editorRef} className="professor-material-rich-editor" contentEditable suppressContentEditableWarning onInput={sync}/>
   <div className="professor-material-editor-footer"><button type="button" className="professor-secondary-button" disabled={saving} onClick={()=>void save('rascunho')}><Save size={17}/> {saving?'Salvando...':'Salvar rascunho'}</button><button type="button" className="professor-primary-button" disabled={saving} onClick={()=>void save('publicado')}><Send size={17}/> Publicar material</button></div>
  </main><aside className="professor-material-editor-side"><div className="professor-material-side-card"><div className="professor-panel-header"><div><span className="professor-eyebrow">Direcionamento</span><h2>Alunos</h2></div><Users size={19}/></div><input className="professor-material-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno..."/><div className="professor-material-student-list">{filtered.map(s=><label key={s.id} className="professor-material-student-option"><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/><span>{s.nome_completo}</span></label>)}</div><small>{selected.length} aluno(s) selecionado(s)</small></div></aside></div>
  {exitDialog&&<div className="professor-material-dialog-backdrop"><div className="professor-material-dialog"><Save size={28}/><h3>Salvar rascunho antes de sair?</h3><p>Suas alterações ainda não foram salvas.</p><div><button type="button" className="professor-secondary-button" onClick={()=>void exit(false)}>Sair sem salvar</button><button type="button" className="professor-primary-button" onClick={()=>void exit(true)}>Salvar rascunho e sair</button></div></div></div>}
 </div>
 return <div className="professor-materials-page"><div className="professor-page-header"><div><span className="professor-eyebrow">Ensino</span><h1>Materiais</h1><p>Crie, edite, salve rascunhos e direcione materiais para um ou mais alunos.</p></div><button type="button" className="professor-primary-button" onClick={newMaterial}><Plus size={18}/> Novo material</button></div>{message&&<div className="professor-material-success">{message}</div>}{error&&<div className="professor-material-error">{error}</div>}{materials.length===0?<div className="professor-materials-empty"><FileText size={40}/><strong>Nenhum material criado</strong><span>Crie seu primeiro material pedagógico.</span></div>:<div className="professor-material-grid">{materials.map(m=><article key={m.id} className="professor-material-card"><div className="professor-material-card-icon"><FileText size={22}/></div><div className="professor-material-card-body"><span>{m.status==='publicado'?'Publicado':'Rascunho'}{m.idioma?' · '+(m.idioma==='ingles'?'Inglês':'Alemão'):''}</span><h3>{m.titulo}</h3><p>Atualizado em {new Date(m.updated_at).toLocaleDateString('pt-BR')}</p></div><div className="professor-material-card-actions"><button type="button" className="professor-secondary-button" onClick={()=>void edit(m)}>Editar</button><button type="button" className="professor-secondary-button" onClick={()=>void view(m)}>Visualizar</button><button type="button" className="professor-icon-danger" onClick={()=>void remove(m)}><Trash2 size={17}/></button></div></article>)}</div>}{viewer&&<div className="professor-material-viewer-modal"><MaterialViewer material={viewer} imageUrls={imageUrls} onClose={()=>setViewer(null)}/></div>}</div>
}