-- Unifica os níveis do sistema em quatro categorias.
alter table public.horarios drop constraint if exists horarios_nivel_referencia_check;
update public.horarios set nivel_referencia=case when nivel_referencia in ('A1','iniciante') then 'iniciante' when nivel_referencia in ('A2','basico','básico') then 'basico' when nivel_referencia in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_referencia in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_referencia end where nivel_referencia is not null;
update public.alunos set nivel_conversacao=case when lower(nivel_conversacao) in ('a1','iniciante') then 'iniciante' when lower(nivel_conversacao) in ('a2','basico','básico') then 'basico' when lower(nivel_conversacao) in ('b1','b2','intermediario','intermediário') then 'intermediario' when lower(nivel_conversacao) in ('c1','c2','avancado','avançado','fluente') then 'avancado' else nivel_conversacao end,nivel_escrita=case when lower(nivel_escrita) in ('a1','iniciante') then 'iniciante' when lower(nivel_escrita) in ('a2','basico','básico') then 'basico' when lower(nivel_escrita) in ('b1','b2','intermediario','intermediário') then 'intermediario' when lower(nivel_escrita) in ('c1','c2','avancado','avançado','fluente') then 'avancado' else nivel_escrita end,nivel_compreensao=case when lower(nivel_compreensao) in ('a1','iniciante') then 'iniciante' when lower(nivel_compreensao) in ('a2','basico','básico') then 'basico' when lower(nivel_compreensao) in ('b1','b2','intermediario','intermediário') then 'intermediario' when lower(nivel_compreensao) in ('c1','c2','avancado','avançado','fluente') then 'avancado' else nivel_compreensao end;
update public.turmas set nivel_referencia=case when nivel_referencia='A1' then 'iniciante' when nivel_referencia='A2' then 'basico' when nivel_referencia in ('B1','B2') then 'intermediario' when nivel_referencia in ('C1','C2') then 'avancado' else nivel_referencia end,nivel_minimo=case when nivel_minimo='A1' then 'iniciante' when nivel_minimo='A2' then 'basico' when nivel_minimo in ('B1','B2') then 'intermediario' when nivel_minimo in ('C1','C2') then 'avancado' else nivel_minimo end,nivel_maximo=case when nivel_maximo='A1' then 'iniciante' when nivel_maximo='A2' then 'basico' when nivel_maximo in ('B1','B2') then 'intermediario' when nivel_maximo in ('C1','C2') then 'avancado' else nivel_maximo end;
update public.turma_participantes set nivel_conversacao=case when nivel_conversacao in ('A1','iniciante') then 'iniciante' when nivel_conversacao in ('A2','basico','básico') then 'basico' when nivel_conversacao in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_conversacao in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_conversacao end,nivel_escrita=case when nivel_escrita in ('A1','iniciante') then 'iniciante' when nivel_escrita in ('A2','basico','básico') then 'basico' when nivel_escrita in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_escrita in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_escrita end,nivel_compreensao=case when nivel_compreensao in ('A1','iniciante') then 'iniciante' when nivel_compreensao in ('A2','basico','básico') then 'basico' when nivel_compreensao in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_compreensao in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_compreensao end;
update public.matricula_proficiencia set nivel_conversacao=case when nivel_conversacao in ('A1','iniciante') then 'iniciante' when nivel_conversacao in ('A2','basico','básico') then 'basico' when nivel_conversacao in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_conversacao in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_conversacao end,nivel_escrita=case when nivel_escrita in ('A1','iniciante') then 'iniciante' when nivel_escrita in ('A2','basico','básico') then 'basico' when nivel_escrita in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_escrita in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_escrita end,nivel_compreensao=case when nivel_compreensao in ('A1','iniciante') then 'iniciante' when nivel_compreensao in ('A2','basico','básico') then 'basico' when nivel_compreensao in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel_compreensao in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel_compreensao end;
update public.leads set nivel=case when nivel in ('A1','iniciante') then 'iniciante' when nivel in ('A2','basico','básico') then 'basico' when nivel in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel end;
update public.candidaturas_professores set nivel=case when nivel in ('A1','iniciante') then 'iniciante' when nivel in ('A2','basico','básico') then 'basico' when nivel in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel end;
update public.professor_permissoes set nivel=case when nivel in ('A1','iniciante') then 'iniciante' when nivel in ('A2','basico','básico') then 'basico' when nivel in ('B1','B2','intermediario','intermediário') then 'intermediario' when nivel in ('C1','C2','avancado','avançado','fluente') then 'avancado' else nivel end;
update public.central_atividades set nivel='avancado' where nivel='fluente';
alter table public.horarios add constraint horarios_nivel_referencia_check check(nivel_referencia is null or nivel_referencia in ('iniciante','basico','intermediario','avancado'));

create or replace function public.nivel_ordem_compatibilidade(p_nivel text) returns integer language sql immutable set search_path to '' as $function$ select case lower(trim(coalesce(p_nivel,''))) when 'iniciante' then 1 when 'basico' then 2 when 'intermediario' then 3 when 'avancado' then 4 when 'fluente' then 4 else null end $function$;

drop function if exists public.criar_turma_fixa_admin_v2(text,text,integer,integer[],text[],text[],uuid,integer,text,date);
create function public.criar_turma_fixa_admin_v2(p_idioma text,p_modalidade text,p_aulas_semana integer,p_dias integer[],p_horas_inicio text[],p_horas_fim text[],p_professor_id uuid,p_quantidade_maxima integer,p_nivel_referencia text,p_data_inicio date) returns uuid language plpgsql security definer set search_path to '' as $function$
declare v_turma_id uuid;v_capacity integer;v_index integer;v_horario_id uuid;
begin
if not exists(select 1 from public.admin_users where user_id=(select auth.uid()) and ativo=true) then raise exception 'Acesso restrito ao administrador.';end if;
if p_modalidade not in ('dupla','grupo') then raise exception 'Modalidade coletiva inválida.';end if;
if p_idioma not in ('ingles','alemao') then raise exception 'Idioma inválido.';end if;
if p_nivel_referencia not in ('iniciante','basico','intermediario','avancado') then raise exception 'Nível de referência inválido.';end if;
if p_data_inicio is null or p_data_inicio<current_date then raise exception 'A data de início deve ser hoje ou uma data futura.';end if;
if p_aulas_semana<1 or p_aulas_semana>3 then raise exception 'A frequência deve estar entre 1 e 3 aulas por semana.';end if;
if coalesce(array_length(p_dias,1),0)<>p_aulas_semana or coalesce(array_length(p_horas_inicio,1),0)<>p_aulas_semana or coalesce(array_length(p_horas_fim,1),0)<>p_aulas_semana then raise exception 'Informe um encontro para cada aula semanal.';end if;
v_capacity:=case when p_modalidade='dupla' then 2 else least(greatest(coalesce(p_quantidade_maxima,6),3),6) end;
if exists(select 1 from unnest(p_dias) as d(day) where d.day<0 or d.day>6) then raise exception 'Dia da semana inválido.';end if;
if (select count(distinct x) from unnest(p_dias) as x)<>p_aulas_semana then raise exception 'Os dias dos encontros devem ser diferentes.';end if;
for v_index in 1..p_aulas_semana loop if p_horas_inicio[v_index]>=p_horas_fim[v_index] then raise exception 'O horário final deve ser maior que o inicial.';end if;end loop;
insert into public.turmas(modalidade,idioma,aulas_semana,quantidade_minima,quantidade_maxima,horario_preferido,status,professor_id,nivel_referencia,nivel_minimo,nivel_maximo,fixa,data_inicio) values(p_modalidade,p_idioma,p_aulas_semana,case when p_modalidade='dupla' then 2 else 3 end,v_capacity,null,'em_formacao',p_professor_id,p_nivel_referencia,p_nivel_referencia,p_nivel_referencia,true,p_data_inicio) returning id into v_turma_id;
for v_index in 1..p_aulas_semana loop
insert into public.horarios(tipo_horario,idioma,dia_semana,hora_inicio,hora_fim,disponivel,aluno_id,professor_id,nivel_referencia) values(p_modalidade,p_idioma,p_dias[v_index],p_horas_inicio[v_index]::time,p_horas_fim[v_index]::time,true,null,p_professor_id,p_nivel_referencia) returning id into v_horario_id;
insert into public.turma_horarios(turma_id,horario_id,ordem) values(v_turma_id,v_horario_id,v_index);
if v_index=1 then update public.turmas set horario_id=v_horario_id where id=v_turma_id;end if;
end loop;return v_turma_id;end;$function$;