import { Bell, BellOff, CheckCircle2, ChevronRight, Clock3, Monitor, RefreshCw, ShieldCheck, Smartphone, TestTube2, XCircle } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
import '../../styles/admin-configuracoes.css'

const VAPID_PUBLIC_KEY='BHHIQyYOOzxLTiMitqMuTFAjWt1bRx472WdEyOOFSqoaql77wk3MRRHDnDd1u0XX8IqjxPHKEymJ8Q26PRSCeJI'
const categories=[['matriculas','Matrículas'],['leads','Leads'],['financeiro','Financeiro'],['alunos','Alunos'],['professores','Professores'],['aulas','Aulas'],['atividades','Atividades'],['sistema','Sistema'],['enterprise','AB Enterprise']] as const
type Tab='push'|'preferencias'|'dispositivos'|'historico'|'teste'
type Preference={categoria:string;push:boolean;interna:boolean}
type Device={id:string;plataforma:string;navegador:string|null;sistema_operacional:string|null;dispositivo:string|null;created_at:string;ultimo_uso_em:string;revogado_em:string|null;endpoint:string}
type NotificationItem={id:string;titulo:string;mensagem:string;categoria:string;prioridade:string;status:string;origem:string;lida:boolean;created_at:string;url:string}

function keyToBytes(value:string){const p='='.repeat((4-value.length%4)%4),raw=atob((value+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function deviceInfo(){const ua=navigator.userAgent;return{browser:/Edg\//.test(ua)?'Edge':/Chrome\//.test(ua)?'Chrome':/Firefox\//.test(ua)?'Firefox':/Safari\//.test(ua)?'Safari':'Navegador',os:/Windows/.test(ua)?'Windows':/Android/.test(ua)?'Android':/iPhone|iPad/.test(ua)?'iOS':/Mac OS/.test(ua)?'macOS':/Linux/.test(ua)?'Linux':'Outro',platform:/Android|iPhone|iPad|Mobile/.test(ua)?'pwa':'web',device:/Android|iPhone|iPad|Mobile/.test(ua)?'PWA Mobile':'Desktop'}}
function relative(value:string){const m=Math.floor((Date.now()-new Date(value).getTime())/60000);if(m<1)return'Agora';if(m<60)return'Há '+m+' min';if(m<1440)return'Há '+Math.floor(m/60)+' h';return new Date(value).toLocaleDateString('pt-BR')}

export default function Configuracoes(){
 const [tab,setTab]=useState<Tab>('push'),[permission,setPermission]=useState<NotificationPermission|'unsupported'>(()=>'Notification'in window?Notification.permission:'unsupported')
 const [prefs,setPrefs]=useState<Preference[]>([]),[devices,setDevices]=useState<Device[]>([]),[history,setHistory]=useState<NotificationItem[]>([])
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[testing,setTesting]=useState(false),[message,setMessage]=useState('')
 const [cat,setCat]=useState('todas'),[priority,setPriority]=useState('todas'),[read,setRead]=useState('todas'),[period,setPeriod]=useState('30')

 const load=useCallback(async()=>{setLoading(true);const [p,d,h]=await Promise.all([
   supabase.from('notification_preferences').select('categoria,push,interna').order('categoria'),
   supabase.from('admin_notificacoes_push_subscriptions').select('id,plataforma,navegador,sistema_operacional,dispositivo,created_at,ultimo_uso_em,revogado_em,endpoint').order('ultimo_uso_em',{ascending:false}),
   supabase.from('admin_notificacoes').select('id,titulo,mensagem,categoria,prioridade,status,origem,lida,created_at,url').order('created_at',{ascending:false}).limit(200)])
   if(!p.error)setPrefs((p.data??[])as Preference[]);if(!d.error)setDevices((d.data??[])as Device[]);if(!h.error)setHistory((h.data??[])as NotificationItem[])
   if(p.error)console.error(p.error);if(d.error)console.error(d.error);if(h.error)console.error(h.error);setLoading(false)},[])
 useEffect(()=>{void load();const ch=supabase.channel('admin-config-notificacoes').on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_notificacoes'},payload=>setHistory(c=>[payload.new as NotificationItem,...c].slice(0,200))).subscribe();return()=>{void supabase.removeChannel(ch)}},[load])

 const current=devices.find(d=>!d.revogado_em),active=devices.filter(d=>!d.revogado_em),pushReady=permission==='granted'&&!!current
 const enablePush=async()=>{setSaving(true);setMessage('');try{if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){setPermission('unsupported');return}const p=await Notification.requestPermission();setPermission(p);if(p!=='granted')return;const reg=await navigator.serviceWorker.ready;const old=await reg.pushManager.getSubscription();const sub=old??await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyToBytes(VAPID_PUBLIC_KEY)});const json=sub.toJSON();const{data:{user}}=await supabase.auth.getUser();if(!user||!json.endpoint||!json.keys?.p256dh||!json.keys.auth)throw new Error('Não foi possível registrar este dispositivo.');const i=deviceInfo();const{error}=await supabase.from('admin_notificacoes_push_subscriptions').upsert({user_id:user.id,endpoint:json.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,plataforma:i.platform,navegador:i.browser,sistema_operacional:i.os,dispositivo:i.device,ultimo_uso_em:new Date().toISOString(),revogado_em:null,updated_at:new Date().toISOString()},{onConflict:'endpoint'});if(error)throw error;setMessage('Notificações Push ativadas neste dispositivo.');await load()}catch(e){console.error(e);setMessage(e instanceof Error?e.message:'Não foi possível ativar as notificações.')}finally{setSaving(false)}}
 const revoke=async(id:string)=>{if(!confirm('Revogar este dispositivo? Ele deixará de receber novas notificações Push.'))return;setSaving(true);const{error}=await supabase.from('admin_notificacoes_push_subscriptions').update({revogado_em:new Date().toISOString()}).eq('id',id);if(error)setMessage('Não foi possível revogar o dispositivo.');else await load();setSaving(false)}
 const updatePref=(categoria:string,field:'push'|'interna',value:boolean)=>setPrefs(c=>c.map(p=>p.categoria===categoria?{...p,[field]:value}:p))
 const savePrefs=async()=>{setSaving(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setMessage('Sessão administrativa não encontrada.');setSaving(false);return}const{error}=await supabase.from('notification_preferences').upsert(prefs.map(p=>({user_id:user.id,categoria:p.categoria,push:p.push,interna:p.interna,updated_at:new Date().toISOString()})),{onConflict:'user_id,categoria'});setMessage(error?'Não foi possível salvar as preferências.':'Preferências salvas.');setSaving(false)}
 const test=async()=>{setTesting(true);setMessage('');try{const{data,error}=await supabase.functions.invoke('admin-push-notification',{body:{action:'test'}});if(error)throw error;setMessage(data?.sent?'Notificação de teste enviada com sucesso.':'Nenhum dispositivo ativo foi encontrado.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível enviar o teste.')}finally{setTesting(false)}}
 const filtered=useMemo(()=>{const cutoff=Date.now()-Number(period)*86400000;return history.filter(n=>new Date(n.created_at).getTime()>=cutoff&&(cat==='todas'||n.categoria===cat)&&(priority==='todas'||n.prioridade===priority)&&(read==='todas'||(read==='lidas'&&n.lida)||(read==='nao_lidas'&&!n.lida)))},[history,cat,priority,read,period])
 if(loading)return <div className="admin-config-loading"><RefreshCw className="is-spinning" size={20}/> Carregando configurações...</div>
 const permissionLabel=permission==='granted'?'Concedida':permission==='denied'?'Bloqueada':permission==='unsupported'?'Não suportada':'Ainda não concedida'
 return <div className="admin-config">
  <div><span className="admin-section-eyebrow">SISTEMA</span><h2 className="admin-section-title">Configurações</h2><p className="admin-section-description">Centralize as preferências administrativas e os canais de notificação do AB Academy.</p></div>
  <div className="admin-config-status"><div><Bell size={17}/><span>Push Notifications</span><strong className={pushReady?'ok':'warning'}>{pushReady?'● Ativo':'⚠ Configuração incompleta'}</strong></div><div><Monitor size={17}/><span>Dispositivo atual</span><strong className={current?'ok':'warning'}>{current?'● Registrado':'○ Não registrado'}</strong></div><div><ShieldCheck size={17}/><span>Permissão</span><strong className={permission==='granted'?'ok':'warning'}>{permissionLabel}</strong></div></div>
  <div className="admin-config-tabs">{[['push','Push'],['preferencias','Preferências'],['dispositivos','Dispositivos'],['historico','Histórico'],['teste','Teste de notificação']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as Tab)}>{label}{id==='dispositivos'&&active.length>0&&<span>{active.length}</span>}</button>)}</div>
  {message&&<div className="admin-config-feedback">{message}<button onClick={()=>setMessage('')} aria-label="Fechar"><XCircle size={15}/></button></div>}
  {tab==='push'&&<div className="admin-config-grid"><section className="admin-config-card"><div className="admin-config-card-icon"><Bell size={20}/></div><span className="admin-section-eyebrow">WEB PUSH</span><h3>Ative as notificações</h3><p>Receba avisos importantes do AB Academy mesmo quando o painel administrativo não estiver aberto.</p>{permission==='denied'?<div className="admin-config-warning"><BellOff size={18}/> As notificações estão bloqueadas no navegador. Libere a permissão nas configurações do navegador.</div>:permission==='unsupported'?<div className="admin-config-warning"><XCircle size={18}/> Este navegador não oferece suporte a Web Push.</div>:<button className="admin-config-primary" onClick={()=>void enablePush()} disabled={saving||permission==='granted'}><Bell size={16}/>{permission==='granted'?'Notificações ativadas':'Ativar notificações'}</button>}</section>
  <section className="admin-config-card"><div className="admin-config-card-heading"><div><span className="admin-section-eyebrow">INFRAESTRUTURA</span><h3>Status</h3></div><CheckCircle2 size={20}/></div><div className="admin-config-status-list"><div><span>Service Worker</span><strong>{'serviceWorker'in navigator?'Disponível':'Indisponível'}</strong></div><div><span>PushManager</span><strong>{'PushManager'in window?'Disponível':'Indisponível'}</strong></div><div><span>Permissão</span><strong>{permissionLabel}</strong></div><div><span>Dispositivo</span><strong>{current?'Registrado':'Não registrado'}</strong></div></div></section></div>}
  {tab==='preferencias'&&<section className="admin-config-card"><div className="admin-config-card-heading"><div><span className="admin-section-eyebrow">PREFERÊNCIAS</span><h3>O que você deseja receber?</h3></div><button className="admin-config-primary compact" onClick={()=>void savePrefs()} disabled={saving}>Salvar preferências</button></div><div>{categories.map(([id,label])=>{const p=prefs.find(x=>x.categoria===id)??{categoria:id,push:true,interna:true};return <div className="admin-config-preference-row" key={id}><div><strong>{label}</strong><span>Defina como este tipo de evento deve chegar.</span></div><label><input type="checkbox" checked={p.push} onChange={e=>updatePref(id,'push',e.target.checked)}/> Push</label><label><input type="checkbox" checked={p.interna} onChange={e=>updatePref(id,'interna',e.target.checked)}/> Interna</label></div>})}</div></section>}
  {tab==='dispositivos'&&<section className="admin-config-card"><div className="admin-config-card-heading"><div><span className="admin-section-eyebrow">DISPOSITIVOS AUTORIZADOS</span><h3>Seus dispositivos</h3></div><button className="admin-config-icon-button" onClick={()=>void load()} aria-label="Atualizar"><RefreshCw size={16}/></button></div><div className="admin-config-devices">{devices.length===0?<div className="admin-config-empty"><Smartphone size={25}/><strong>Nenhum dispositivo registrado</strong><span>Ative as notificações Push neste navegador para começar.</span></div>:devices.map(d=><div className={'admin-config-device '+(d.revogado_em?'revoked':'')} key={d.id}><div className="admin-config-device-icon">{d.plataforma==='pwa'?<Smartphone size={19}/>:<Monitor size={19}/>}</div><div className="admin-config-device-copy"><strong>{d.dispositivo||d.navegador||'Dispositivo'}</strong><span>{d.navegador||'Web'} · {d.sistema_operacional||'Sistema não identificado'}</span><small>{d.revogado_em?'Revogado':'Ativo · último uso '+relative(d.ultimo_uso_em)}</small></div>{!d.revogado_em&&<button className="admin-config-revoke" onClick={()=>void revoke(d.id)} disabled={saving}>Revogar</button>}</div>)}</div></section>}
  {tab==='historico'&&<section className="admin-config-card"><div className="admin-config-card-heading"><div><span className="admin-section-eyebrow">HISTÓRICO</span><h3>Notificações processadas</h3></div><button className="admin-config-icon-button" onClick={()=>void load()} aria-label="Atualizar"><RefreshCw size={16}/></button></div><div className="admin-config-filters"><select value={cat} onChange={e=>setCat(e.target.value)}><option value="todas">Todas as categorias</option>{categories.map(([id,l])=><option value={id} key={id}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="todas">Todas as prioridades</option><option value="informativa">Informativa</option><option value="importante">Importante</option><option value="critica">Crítica</option></select><select value={read} onChange={e=>setRead(e.target.value)}><option value="todas">Todas</option><option value="lidas">Lidas</option><option value="nao_lidas">Não lidas</option></select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></div><div className="admin-config-history">{filtered.length===0?<div className="admin-config-empty"><Clock3 size={25}/><strong>Nenhuma notificação encontrada</strong></div>:filtered.map(n=><button className={'admin-config-history-row '+(n.lida?'read':'unread')} key={n.id} onClick={()=>n.url&&(window.location.href=n.url)}><span className={'priority priority-'+n.prioridade}>{n.prioridade}</span><span className="history-copy"><strong>{n.titulo}</strong><span>{n.mensagem}</span><small>{n.categoria} · {relative(n.created_at)} · {n.origem}</small></span><ChevronRight size={16}/></button>)}</div></section>}
  {tab==='teste'&&<section className="admin-config-card"><div className="admin-config-card-icon"><TestTube2 size={20}/></div><span className="admin-section-eyebrow">DIAGNÓSTICO</span><h3>Enviar notificação de teste</h3><p>Valide o dispositivo atual e o envio Web Push sem alterar nenhum fluxo de negócio.</p><div className="admin-config-test-summary"><div><span>Permissão</span><strong>{permissionLabel}</strong></div><div><span>Dispositivo</span><strong>{current?'Registrado':'Não registrado'}</strong></div><div><span>Push</span><strong>{pushReady?'Pronto':'Não pronto'}</strong></div></div>{!current||permission!=='granted'?<button className="admin-config-primary" onClick={()=>void enablePush()} disabled={saving}><Bell size={16}/> Ativar neste dispositivo</button>:<button className="admin-config-primary" onClick={()=>void test()} disabled={testing}><TestTube2 size={16}/>{testing?'Enviando...':'Enviar notificação de teste'}</button>}</section>}
 </div>
}
