import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronDown, ChevronUp, Clock3, Mail, MessageCircle, Phone, Save, Search, UserPlus } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Lead={id:string;nome:string;email:string;telefone:string;idioma_interesse:string;objetivo:string|null;nivel:string|null;origem:string;landing_page:string|null;source:string|null;medium:string|null;campaign:string|null;term:string|null;content:string|null;referrer:string|null;status:string;observacoes:string|null;contacted_at:string|null;created_at:string;updated_at:string}
const statuses=[['novo','Novo'],['contatado','Contatado'],['diagnostico','Diagnóstico'],['proposta_enviada','Proposta enviada'],['negociacao','Negociação'],['matriculado','Matriculado'],['perdido','Perdido']]
const langs:Record<string,string>={ingles:'Inglês',alemao:'Alemão',ambos:'Inglês + Alemão'}
const date=(v:string)=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})
const whatsappNumber='5511999738440'

export default function Leads(){const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filter,setFilter]=useState('todos'),[open,setOpen]=useState<string|null>(null),[saving,setSaving]=useState<string|null>(null),[drafts,setDrafts]=useState<Record<string,string>>({})
useEffect(()=>{void load()},[])
async function load(){setLoading(true);const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false});if(error){console.error(error);setLeads([])}else{const x=(data||[]) as Lead[];setLeads(x);setDrafts(Object.fromEntries(x.map(l=>[l.id,l.observacoes||''])))}setLoading(false)}
async function status(l:Lead,s:string){setSaving(l.id);const now=new Date().toISOString();const {error}=await supabase.from('leads').update({status:s,contacted_at:s==='contatado'?now:l.contacted_at,updated_at:now}).eq('id',l.id);if(!error)setLeads(x=>x.map(i=>i.id===l.id?{...i,status:s,contacted_at:s==='contatado'?now:i.contacted_at}:i));else console.error(error);setSaving(null)}
async function note(l:Lead){setSaving(l.id);const observation=drafts[l.id]?.trim()||null;const {error}=await supabase.from('leads').update({observacoes:observation,updated_at:new Date().toISOString()}).eq('id',l.id);if(!error)setLeads(x=>x.map(i=>i.id===l.id?{...i,observacoes:observation}:i));else console.error(error);setSaving(null)}
function whatsapp(l:Lead){const firstName=l.nome.trim().split(/\s+/)[0]||'Olá';const message=`Olá, ${firstName}! Aqui é da AB Academy. Recebemos seu interesse em ${langs[l.idioma_interesse]||'idiomas'} e gostaria de saber como podemos ajudar você a começar. 😊`;return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`}
function openWhatsApp(l:Lead){window.open(whatsapp(l),'_blank','noopener,noreferrer');if(l.status==='novo')void status(l,'contatado')}
const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return leads.filter(l=>(filter==='todos'||l.status===filter)&&(!q||[l.nome,l.email,l.telefone,l.campaign||'',l.source||''].some(v=>v.toLowerCase().includes(q))))},[leads,search,filter])
return <div className="admin-leads"><div className="admin-leads-header"><div><span className="admin-leads-eyebrow">Captação B2C</span><h2>Leads</h2><p>Centralize os interessados em estudar na AB Academy e acompanhe cada oportunidade até a matrícula.</p></div><div className="admin-leads-summary"><strong>{leads.filter(l=>l.status==='novo').length}</strong><span>novos</span><b>{leads.length}</b><span>totais</span></div></div>
<div className="admin-leads-funnel">{statuses.map(([v,l])=><button type="button" key={v} className={filter===v?'active':''} onClick={()=>setFilter(filter===v?'todos':v)}><strong>{leads.filter(x=>x.status===v).length}</strong><span>{l}</span></button>)}</div>
<div className="admin-leads-toolbar"><label className="admin-leads-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, e-mail, telefone ou campanha"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos os status</option>{statuses.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>
{loading?<div className="admin-leads-empty">Carregando leads...</div>:!filtered.length?<div className="admin-leads-empty"><UserPlus size={25}/><strong>Nenhum lead encontrado.</strong><span>Os contatos enviados pelo site aparecerão aqui.</span></div>:<div className="admin-leads-list">{filtered.map(l=>{const isOpen=open===l.id;return <article className="admin-lead-card" key={l.id}><div className="admin-lead-heading"><div><span className="admin-lead-date">{date(l.created_at)}</span><h3>{l.nome}</h3><p>{l.email} · {langs[l.idioma_interesse]||l.idioma_interesse}</p></div><div className="admin-lead-actions"><select value={l.status} disabled={saving===l.id} onChange={e=>void status(l,e.target.value)} className={'admin-lead-status status-'+l.status}>{statuses.map(([v,x])=><option value={v} key={v}>{x}</option>)}</select><button type="button" className="admin-lead-details" onClick={()=>setOpen(isOpen?null:l.id)}>{isOpen?<ChevronUp size={16}/>:<ChevronDown size={16}/>} {isOpen?'Fechar':'Detalhes'}</button></div></div><div className="admin-lead-contact"><a href={'mailto:'+l.email}><Mail size={15}/>{l.email}</a><a href={'tel:'+l.telefone}><Phone size={15}/>{l.telefone}</a><button type="button" className="admin-lead-whatsapp" onClick={()=>openWhatsApp(l)}><MessageCircle size={15}/>WhatsApp</button>{l.status==='contatado'&&<span className="admin-lead-contacted"><Check size={14}/> Contatado</span>}{l.objetivo&&<span>Objetivo: {l.objetivo}</span>}{l.nivel&&<span>Nível: {l.nivel}</span>}</div>{isOpen&&<div className="admin-lead-expanded"><div className="admin-lead-data"><div><strong>Origem</strong><span>{l.source||l.origem||'site'}</span></div><div><strong>Campanha</strong><span>{l.campaign||'—'}</span></div><div><strong>Mídia</strong><span>{l.medium||'—'}</span></div><div><strong>Landing page</strong><span>{l.landing_page||'—'}</span></div><div><strong>Referência</strong><span>{l.referrer||'Direto'}</span></div></div><section className="admin-lead-notes"><div className="admin-lead-section-heading"><div><span>Gestão interna</span><h4>Observações</h4></div><Clock3 size={17}/></div><textarea value={drafts[l.id]||''} onChange={e=>setDrafts(x=>({...x,[l.id]:e.target.value}))} placeholder="Próximos passos, contatos, diagnóstico, proposta..." rows={4}/><button type="button" disabled={saving===l.id} onClick={()=>void note(l)}><Save size={15}/>{saving===l.id?'Salvando...':'Salvar observação'}</button></section></div>}</article>})}</div>}</div>}
