name: Frontend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Validate npm install
        run: npm install

      - name: Install dependencies with clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
